export type Nutrients = {
    energy_kcal?: number;
    energy_kcal_100?: number;
    energy_kj?: number;
    energy_kj_100?: number;
    fat?: number;
    fat_100?: number;
    saturated_fat: number;
    saturated_fat_100?: number;
    carbohydrates: number;
    carbohydrates_100?: number;
    sugars: number;
    sugars_100?: number;
    proteins: number;
    proteins_100?: number;
    fiber: number;
    fiber_100?: number;
    salt?: number;
    salt_100?: number;
    sodium?: number;
    sodium_100?: number;
};
